name: spinrates-env
channels:
  - conda-forge
dependencies:
  - pandas
  - matplotlib
  - numpy
  - pip
  - pyarrow
  - fastparquet
  - python-snappy
  - "s3fs==2021.05.0"
  - boto3
  - aiobotocore
  - pip:
    - streamlit
