name: spinrates-env
channels:
  - conda-forge
dependencies:
  - pandas
  - matplotlib
  - numpy
  - pip
  - pyarrow
  - fsspec
  - s3fs
  - boto3
  - aiobotocore
  - pip:
    - streamlit
    - pybaseball
    - python-dotenv