name: spinrates-env
channels:
  - conda-forge
dependencies:
  - pandas
  - matplotlib
  - numpy
  - pip
  - pyarrow
  - "fsspec==2021.05.0"
  - "s3fs==2021.05.0"
  - boto3
  - aiobotocore
  - pip:
    - streamlit
    - pybaseball
    - python-dotenv
